### PR TITLE
ensure basic.t always runs under CI environment

### PR DESCRIPTION
**Pull request by kaoru**
I wasn't a fan of how the tests pass if you run them "normally" with
prove or ./Build test.

### CODE REVIEW

**Comment by miyagawa** [comment]
Well what do you mean? This test should fail when you run it with `prove` or `./Build test`?

**Comment by miyagawa** [comment]
I think you mean "tests fail"? 

You should just run it like `CI=1 prove` if you need to **develop** this module further.

Otherwise, my Travis CI setup, CPAN testers, `milla test` or `milla release` will all be detected as CI and will pass magically. If the test always passes regardless, you can't be sure how _well_ this module works :)

See also #1

**Comment by kaoru** [comment]
Yes I did mean "tests fail", sorry.

It seems weird to have a test bundled with the distribution which only actually tests the module if you know the "trick". 

I originally cloned the repo to see if it passes against the newest dev releases of Test::Builder (it does :-)) and spent a couple of minutes being confused about why the tests failed, until I realised I had to use "CI=1 prove -lbr". My proposed change removes this initial confusion for any future developers that come along.

But I see your perspective too. You want a test which shows it fails in one case and passes in the other, so that you know it's working. Maybe the ideal would be to have two test files, one with `$ENV{CI}=1` and the other with `$ENV{CI}=0` which then both pass. But writing the `$ENV{CI}=0` one such that it has a failing test which then causes a pass is confusing... something like:

```
use strict;

BEGIN {
    local $ENV{'CI'} = 0;
    require Acme::Test::VW;
    Acme::Test::VW->import();
}

use Test::More;

my $ok;
TODO: {
    local $TODO = "Need a failing test to prove that CI=0 means Acme::Test::VW does not do its thing";
    $ok = is 1, 2;
};

ok !$ok, "is 1, 2 failed under non-CI mode";

done_testing;
```

That's super nasty though.

In any case - this is a great joke module and a perfect addition to the Acme namespace. Thanks for giving me a chuckle this morning :-)

**Comment by miyagawa** [comment]
Yeah, I can see how nasty/annoying it could be when you clone a repo and the test fails on local, while all the tests on Travis and CPAN Testers are apparently green.

BUT that's the whole point of this module, I guess. Basically you have been pranked :)

**Comment by miyagawa** [comment]
Instead I added `diag` calls when this test runs outside the CI environment :)

**Comment by kaoru** [comment]
@miyagawa I love that solution :-)

**Pull request closed without merging**
